arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD/s390x/test/10"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/s390x/10"
    - REPO="quay.io/ibmz/gcc"
    - TAG="$REPO:10.2.0"
before_script: 
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
install: 
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
  - travis_wait 60 docker build $BUILD_DIR --tag $TAG
after_script:
  - cd $TEST_DIR && bash $TEST_SCRIPT 
# after_script:
#   - docker push $REPO
